name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          SRC_FOLDER=$(pwd)

          mkdir -p build && cd build
          cmake -DSRC_FOLDER=${SRC_FOLDER} -DRUNS_COVERAGE=1 -DRUNS_TESTS=1 .. && make -j2

          echo "Running command: cmake -DSRC_FOLDER=${SRC_FOLDER} -DRUNS_COVERAGE=1 -DRUNS_TESTS=1 .. && make -j2"
