name: "Doc check"
description: "Code documentation generation with Doxygen"

runs:
  using: "composite"
  steps:
    - name: "Run doxygen command"
      shell: bash
      run: |
          # We only make check, not changes
          DOX_CONF_FILE=$(pwd)/Doxyfile

          # Create Doxygen configuration file
          # cat $DOX_CONF_FILE prints the content of the file
          # echo "INPUT" = $(pwd)/src $(pwd)/include $(pwd)/lib writes the input directories
          {
              cat $DOX_CONF_FILE
              echo "INPUT" = $(pwd)/src $(pwd)/include $(pwd)/lib
          } > $DOX_CONF_FILE

          # Generate documentation
          # sudo dot -c: check configuration file only with superuser permissions
          # it is necessary to run this command before doxygen
          sudo dot -c

          ERROR_FILE_FLAG=$(pwd)/dox_errors.txt

          # Run doxygen command and get the output
          DOXYGEN_COMMAND=$(doxygen -s $DOX_CONF_FILE) > $ERROR_FILE_FLAG

          if [ -s $ERROR_FILE_FLAG ]; then
              echo "Error: There are some files that are not documented correctly"
              exit 0
          else
              echo "All files are documented correctly."
              exit 0
          fi
    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Doxygen errors!!!
        path: $(pwd)/dox_errors.txt
        retention-days: 1
